#ifndef SERIAL_BAUD
#define SERIAL_BAUD 115200
#endif
#ifndef SERIAL_DEBUG_ENABLE
#define SERIAL_DEBUG_ENABLE true
#endif

#ifndef CPU_FREQ_MHZ
#define CPU_FREQ_MHZ 80
#endif
#ifndef CPU_FREQ_ONDEMAND
#define CPU_FREQ_ONDEMAND 80
#endif
#define CPU_FREQ_MHZ_MIN_RADIO 80
#ifndef CPU_FREQ_MHZ_NORADIO
#define CPU_FREQ_MHZ_NORADIO 10
#endif

#define I2C_FREQ_STD 100000
#define I2C_FREQ_FAST 400000
#define I2C_FREQ_SLOW 10000
#define I2C_FREQ_SUPER 1000000

#ifndef I2C_FREQ_DEFAULT
#define I2C_FREQ_DEFAULT I2C_FREQ_STD
#endif

#define BATTERY_MAGIC_MULTIPLIER 0.91911764705 

#define NTP_POOL "europe.pool.ntp.org"
#define NTP_OFFSET 1

#define SLEEPTUNE_LOOPS_PER_TIMING_REPORT SLEEPTUNE_LOOPS_PER_SECOND * 120
#define SLEEPTUNE_INITIAL_SLEEP_MS 1000 / SLEEPTUNE_LOOPS_PER_SECOND
#define SLEEPTUNE_TUNING_STEP_MS 2

#define ENABLE_BLUETOOTH
#define BT_BLE_UART_MAX_PACKET 20
#define BT_BLE_UART_DEBUG false

#define ENABLE_WIFI
#ifndef WIFI_PS_NONE
#define WIFI_PS_NONE 0
#define WIFI_PS_MIN_MODEM 2
#define WIFI_PS_MAX_MODEM 3
#endif